/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tron_common_zksnark_LibrustzcashJni */

#ifndef _Included_org_tron_common_zksnark_LibrustzcashJni
#define _Included_org_tron_common_zksnark_LibrustzcashJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tron_common_zksnark_LibrustzcashJni
 * Method:    librustzcashCheckDiversifier
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_tron_common_zksnark_LibrustzcashJni_librustzcashCheckDiversifier
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
