package org.tron.core.consensus.base;

public enum Status {
  OK,
  LAG,
  UNELECTED,
  TIME_OUT,
  CLOCK_ERROR,
  NOT_SYNCED,
  DUP_WITNESS,
  NOT_MY_TURN,
  NOT_TIME_YET,
  NO_PRIVATE_KEY,
  WITNESS_PERMISSION_ERROR,
  LOW_PARTICIPATION,
  CONSECUTIVE,
  BACKUP_STATUS_IS_NOT_MASTER,
  EXCEPTION_PRODUCING_BLOCK
}
